# .pre-commit-config.yaml

repos:
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        # Define o comprimento máximo da linha para 88 caracteres (padrão do Black)
        args: [--line-length=88]

-   repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        # Define o perfil de compatibilidade com o Black
        args: ["--profile", "black", "--line-length=88"]