# dre  = yf.Ticker(self.ativo + ".SA").financials


BALANCOS = {
    "dre_original": [
        "Operating Revenue",
        "Total Revenue",
        "Cost Of Revenue",
        "Gross Profit",
        "General And Administrative Expense",
        "Selling And Marketing Expense",
        "Selling General And Administration",
        "Other Operating Expenses",
        "Operating Expense",
        "Operating Income",
        "Interest Income Non Operating",
        "Interest Expense Non Operating",
        "Total Other Finance Cost",
        "Net Non Operating Interest Income Expense",
        "Restructuring And Mergern Acquisition",
        "Special Income Charges",
        "Pretax Income",
        "Tax Provision",
        "Net Income Continuous Operations",
        "Net Income Including Noncontrolling Interests",
        "Minority Interests",
        "Net Income",
        "Otherunder Preferred Stock Dividend",
        "Net Income Common Stockholders",
        "Diluted NI Availto Com Stockholders",
        "Basic EPS",
        "Diluted EPS",
        "Basic Average Shares",
        "Diluted Average Shares",
        "Total Expenses",
        "Net Income From Continuing And Discontinued Operation",
        "Normalized Income",
        "Interest Income",
        "Interest Expense",
        "Net Interest Income",
        "EBIT",
        "EBITDA",
        "Reconciled Cost Of Revenue",
        "Reconciled Depreciation",
        "Net Income From Continuing Operation Net Minority Interest",
        "Total Unusual Items Excluding Goodwill",
        "Total Unusual Items",
        "Normalized EBITDA",
        "Tax Rate For Calcs",
        "Tax Effect Of Unusual Items",
    ],
    "dre": {
        "Total Revenue": "receita_total",
        "Cost Of Revenue": "custo_receita",
        "Gross Profit": "lucro_bruto",
        "Operating Expense": "despesa_operacional",
        "Operating Income": "lucro_operacional",
        "Pretax Income": "lucro_antes_impostos",
        "Tax Provision": "provisao_impostos",
        "Net Income Common Stockholders": "lucro_liquido",
        "Basic EPS": "eps",
        "Total Expenses": "despesas_totais",
        "Normalized Income": "lucro_normalizado",
        "Interest Income": "juros_recebidos",
        "Interest Expense": "juros_pagos",
        "Net Interest Income": "lucro_juros",
        "EBIT": "ebit",
        "EBITDA": "ebitda",
        "Reconciled Depreciation": "depreciacao",
        "Normalized EBITDA": "ebitda_normalizado",
    },
    "bp_orig": [
        "Cash Financial",
        "Cash Equivalents",
        "Cash And Cash Equivalents",
        "Other Short Term Investments",
        "Cash Cash Equivalents And Short Term Investments",
        "Gross Accounts Receivable",
        "Allowance For Doubtful Accounts Receivable",
        "Accounts Receivable",
        "Taxes Receivable",
        "Raw Materials",
        "Work In Process",
        "Finished Goods",
        "Other Inventories",
        "Inventories Adjustments Allowances",
        "Inventory",
        "Hedging Assets Current",
        "Other Current Assets",
        "Current Assets",
        "Properties",
        "Land And Improvements",
        "Buildings And Improvements",
        "Machinery Furniture Equipment",
        "Other Properties",
        "Construction In Progress",
        "Gross PPE",
        "Accumulated Depreciation",
        "Net PPE",
        "Goodwill",
        "Other Intangible Assets",
        "Goodwill And Other Intangible Assets",
        "Investmentsin Subsidiariesat Cost",
        "Investmentsin Associatesat Cost",
        "Long Term Equity Investment",
        "Trading Securities",
        "Investmentin Financial Assets",
        "Financial Assets",
        "Non Current Deferred Taxes Assets",
        "Other Non Current Assets",
        "Total Non Current Assets",
        "Total Assets",
        "Accounts Payable",
        "Total Tax Payable",
        "Dividends Payable",
        "Other Payable",
        "Payables",
        "Current Provisions",
        "Pensionand Other Post Retirement Benefit Plans Current",
        "Current Debt",
        "Current Capital Lease Obligation",
        "Current Debt And Capital Lease Obligation",
        "Other Current Liabilities",
        "Current Liabilities",
        "Long Term Provisions",
        "Long Term Debt",
        "Long Term Capital Lease Obligation",
        "Long Term Debt And Capital Lease Obligation",
        "Non Current Deferred Taxes Liabilities",
        "Tradeand Other Payables Non Current",
        "Derivative Product Liabilities",
        "Other Non Current Liabilities",
        "Total Non Current Liabilities Net Minority Interest",
        "Total Liabilities Net Minority Interest",
        "Common Stock",
        "Capital Stock",
        "Treasury Stock",
        "Other Equity Interest",
        "Stockholders Equity",
        "Minority Interest",
        "Total Equity Gross Minority Interest",
        "Total Capitalization",
        "Common Stock Equity",
        "Capital Lease Obligations",
        "Net Tangible Assets",
        "Working Capital",
        "Invested Capital",
        "Tangible Book Value",
        "Total Debt",
        "Share Issued",
        "Ordinary Shares Number",
        "Treasury Shares Number",
    ],
    "bp": {
        "Cash And Cash Equivalents": "caixa_equivalentes_caixa",
        "Current Assets": "ativo_circulante",
        "Goodwill And Other Intangible Assets": "goodwill_ativos_intangiveis",
        "Long Term Equity Investment": "investimentos_longo_prazo",
        "Total Non Current Assets": "ativo_nao_circulante",
        "Total Assets": "ativos_totais",
        "Dividends Payable": "dividendos_a_pagar",
        "Current Debt": "divida_curto_prazo",
        "Current Liabilities": "passivos_curto_prazo",
        "Long Term Debt": "divida_longo_prazo",
        "Total Non Current Liabilities Net Minority Interest": "passivo_nao_circulante",
        "Total Liabilities Net Minority Interest": "passivos_totais",
        "Stockholders Equity": "patrimonio_liquido",
        "Total Capitalization": "capitalizacao_total",
        "Net Tangible Assets": "ativos_tangiveis",
        "Working Capital": "capital_de_giro",
        "Invested Capital": "capital_investido",
        "Tangible Book Value": "valor_contabil",
        "Total Debt": "divida_total",
        "Ordinary Shares Number": "numero_acoes_ordinarias",
        "Treasury Shares Number": "numero_acoes_em_tesouraria",
    },
    "fc_orig": [
        "Net Income From Continuing Operations",
        "Depreciation And Amortization",
        "Change In Working Capital",
        "Operating Cash Flow",
        "Investing Cash Flow",
        "Cash Dividends Paid",
        "Financing Cash Flow",
        "Changes In Cash",
        "Beginning Cash Position",
        "End Cash Position",
        "Capital Expenditure",
        "Issuance Of Capital Stock",
        "Issuance Of Debt",
        "Repayment Of Debt",
        "Repurchase Of Capital Stock",
        "Free Cash Flow",
    ],
    "fc": {
        "Net Income From Continuing Operations": "lucro_liquido",
        "Depreciation And Amortization": "depreciacao_e_amortizacao",
        "Change In Working Capital": "variacao_capital_de_giro",
        "Operating Cash Flow": "fluxo_caixa_operacional",
        "Investing Cash Flow": "fluxo_caixa_investimentos",
        "Cash Dividends Paid": "dividendos_pagos",
        "Financing Cash Flow": "fluxo_caixa_financiamento",
        "Changes In Cash": "variaca_do_caixa",
        "Beginning Cash Position": "posicao_inicial_caixa",
        "End Cash Position": "posicao_final_caixa",
        "Issuance Of Capital Stock": "emissao_acoes",
        "Issuance Of Debt": "emissao_dividas",
        "Repayment Of Debt": "pagamento_dividas",
        "Repurchase Of Capital Stock": "compra_acoes",
        "Free Cash Flow": "fluxo_caixa_livre",
    },
}
